#!/bin/sh
set -eu

CONFIG_FILE=${JLSHELL_LINK_AGENT_CONFIG:-"${HOME:?}/.config/jlshell-link-agent/agent.env"}
if [ ! -f "$CONFIG_FILE" ] || [ -L "$CONFIG_FILE" ]; then
    printf '%s\n' 'JLShell Link Agent 配置必须是当前用户的普通文件' >&2
    exit 1
fi
# The configuration is generated by install-user-service.sh with shell-safe quoting.
. "$CONFIG_FILE"

set -- "${JAVA:-java}" -jar "$JLSHELL_LINK_AGENT_JAR" run \
    --state-dir "$JLSHELL_LINK_STATE_DIR" \
    --link-wss "$JLSHELL_LINK_WSS_URI" \
    --tls-identity-p12 "$JLSHELL_LINK_TLS_IDENTITY" \
    --tls-password-file "$JLSHELL_LINK_TLS_PASSWORD_FILE" \
    --allowed-targets-file "$JLSHELL_LINK_ALLOWED_TARGETS"
if [ -n "${JLSHELL_LINK_TICKET_ISSUER:-}" ]; then
    set -- "$@" --ticket-issuer "$JLSHELL_LINK_TICKET_ISSUER"
fi
exec "$@"
